Repository GarbyX/SpringBoot_RBAC, pull requests merged in 2023-05, with the labels that each got.

#2 garby -> dev
  pom.xml
Labels: documentation, enhancement

#4 garby -> dev
  src/main/java/com/garby/rbac/controllers/ProductController.java
  src/main/java/com/garby/rbac/models/Product.java
  src/main/java/com/garby/rbac/repositories/ProductRepository.java
  src/main/java/com/garby/rbac/services/ProductService.java
  src/main/resources/application-dev.yaml
  src/main/resources/application-prod.yaml
  src/main/resources/application.properties
  src/main/resources/application.yaml
  src/main/resources/templates/index.html
Labels: documentation, good first issue

#5 dev -> master
  pom.xml
  src/main/java/com/garby/rbac/controllers/ProductController.java
  src/main/resources/application.properties
  src/main/resources/templates/index.html
Labels: documentation

#7 Garby
  src/main/java/com/garby/rbac/controllers/ProductController.java
  src/main/java/com/garby/rbac/models/Product.java
  src/main/resources/templates/new_product.html
Labels: enhancement

#8 dev - master
  src/main/java/com/garby/rbac/controllers/ProductController.java
Labels: enhancement
